language: node_js
node_js:
  - "7"

before_install: npm install -g gulp-cli
script: ./tools/scripts/travis.sh
deploy:
  skip_cleanup: true
  provider: script
  script: tools/scripts/deploy.sh
  on:
    tags: true
    condition: $(git branch --contains $TRAVIS_TAG | grep -q '^[\* ] master$')
addons:
  apt:
    packages:
      - sshpass
